### ISSUE TITLE
Support YAML

### ISSUE THREAD

**Issue by matthewadams** [Jasonette/documentation#35]
YAML is a terser format than JSON, and JSON is a subset of YAML; that is, valid JSON is also valid YAML, so there would be no backward compatibility issues.

For example, converting https://imagejason.herokuapp.com yields the document below.  Some might find this format preferable.

```
---
"$jason":
  head:
    title: image sample
    data:
      db:
      - _id: 58a63ebabb7fa20400ab5b9d
        url: https://s3-us-west-2.amazonaws.com/fm.ethan.jason/223FAE7F-6025-470D-8367-7E7EB6434B08.jpeg
        __v: 0
      - _id: 58a408b246c81004001fbc7f
        url: https://s3-us-west-2.amazonaws.com/fm.ethan.jason/3C0FFB05-3B6B-4F46-A084-6CF74C465410.jpeg
        __v: 0
      - _id: 5888b9986029e204008ee021
        url: https://s3-us-west-2.amazonaws.com/fm.ethan.jason/095DFFE3-8BEE-4683-A5EE-6CC607AA094D.jpeg
        __v: 0
      - _id: 588795f6ee17f50400cefd1e
        url: https://s3-us-west-2.amazonaws.com/fm.ethan.jason/1119278C-8C49-45D2-B402-1E8BA9753E2E.jpeg
        __v: 0
      - _id: 587b07c3b58c750400eeb978
        url: https://s3-us-west-2.amazonaws.com/fm.ethan.jason/D7D03190-88F3-429B-9F6D-0E710B87681A.jpeg
        __v: 0
      - _id: 587b0765b58c750400eeb977
        url: https://s3-us-west-2.amazonaws.com/fm.ethan.jason/0C78B00B-7613-4973-8EC9-F5F681B03948.jpeg
        __v: 0
      - _id: 586f1f8f7da7450400c0aaea
        url: https://s3-us-west-2.amazonaws.com/fm.ethan.jason/7DAA7B7F-63FF-40FF-94A3-925FF5909C4C.jpeg
        __v: 0
      - _id: 586dc151424b2a0400c157e5
        url: https://s3-us-west-2.amazonaws.com/fm.ethan.jason/0D674AC2-8EB8-4FF8-9441-F6C3FD796A3D.jpeg
        __v: 0
      - _id: 586dbbf7424b2a0400c157e4
        url: https://s3-us-west-2.amazonaws.com/fm.ethan.jason/06538FBF-8150-491E-AD4D-A3D86008FA5A.jpeg
        __v: 0
      - _id: 586bf598d928ff04009cf0f5
        url: https://s3-us-west-2.amazonaws.com/fm.ethan.jason/FB201FED-ECDF-4E9D-B64F-131A0FF3A956.jpeg
        __v: 0
      - _id: 5867543679eb6b0400a34e1b
        url: https://s3-us-west-2.amazonaws.com/fm.ethan.jason/6EA56BBE-36BB-4583-8EBA-754DFB75820A.jpeg
        __v: 0
      - _id: 58572ebf2915d60400f0e020
        url: https://s3-us-west-2.amazonaws.com/fm.ethan.jason/14C6F89B-D220-4490-8710-F85A9CAA130E.jpeg
        __v: 0
      - _id: 5853855f4c24b70400ac4ac3
        url: https://s3-us-west-2.amazonaws.com/fm.ethan.jason/E043A6EF-2247-4D17-A63A-8625A3DDE623.jpeg
        __v: 0
      - _id: 584dfbe3a38e9304003fe34a
        url: https://s3-us-west-2.amazonaws.com/fm.ethan.jason/6D860BE2-202A-4471-B115-02FDE24DBAE9.jpeg
        __v: 0
      - _id: 583ad05e2ade400400cade37
        url: https://s3-us-west-2.amazonaws.com/fm.ethan.jason/B6332326-9C4B-4878-B908-EE7C74A6BC89.jpeg
        __v: 0
      - _id: 5837bbbc3e351a040000f256
        url: https://s3-us-west-2.amazonaws.com/fm.ethan.jason/353399FF-5658-4C4B-87DE-4E57F77F8E11.jpeg
        __v: 0
      - _id: 5837bb993e351a040000f255
        url: https://s3-us-west-2.amazonaws.com/fm.ethan.jason/291C2C62-6DBC-401D-A04A-F83E81DC5C89.jpeg
        __v: 0
      - _id: 582f74ae7d5cbc0400353651
        url: https://s3-us-west-2.amazonaws.com/fm.ethan.jason/52D80F3E-F155-43F3-A1A9-0EECA5B3E92B.jpeg
        __v: 0
      - _id: 582a7c29943e050400369d78
        url: https://s3-us-west-2.amazonaws.com/fm.ethan.jason/6D38F3DE-15DC-40E8-BFC4-665E567DB650.jpeg
        __v: 0
      - _id: 5828ee24ecbbb90400f719d7
        url: https://s3-us-west-2.amazonaws.com/fm.ethan.jason/EF149342-E05D-4B32-94A6-4EB840527984.jpeg
        __v: 0
      - _id: 582237369eb108040063173d
        url: https://s3-us-west-2.amazonaws.com/fm.ethan.jason/5771CEA9-F1DD-4502-8671-5EEFE85C7504.jpeg
        __v: 0
      - _id: 5821fb7b802f060300c0a337
        url: https://s3-us-west-2.amazonaws.com/fm.ethan.jason/ECEB2B7B-B8F9-404C-BADF-3C9AE59763F8.jpeg
        __v: 0
      - _id: 5821d01848751c03007bda8b
        url: https://s3-us-west-2.amazonaws.com/fm.ethan.jason/BB43115A-C3FA-4CD6-89BD-214ACD5DF8A2.jpeg
        __v: 0
      - _id: 5821cffc48751c03007bda8a
        url: https://s3-us-west-2.amazonaws.com/fm.ethan.jason/FCA699B4-C750-4F1C-B812-5C083E8C78B0.jpeg
        __v: 0
      - _id: 5821a039881ec5030008c3ea
        url: https://s3-us-west-2.amazonaws.com/fm.ethan.jason/CF60C612-66D6-43A2-9D56-6A708BECAFC2.jpeg
        __v: 0
      - _id: 582160f1b364ab0300ffe4e2
        url: https://s3-us-west-2.amazonaws.com/fm.ethan.jason/BD71DDA7-9F3B-4A3C-9DC5-A9D1D2603CFD.jpeg
        __v: 0
      - _id: 5820c2963bc8e703007433a0
        url: https://s3-us-west-2.amazonaws.com/fm.ethan.jason/F04BCB1B-60D8-42EB-835E-3D20B58B9340.jpeg
        __v: 0
      - _id: 581ff3af8d42060300c834dd
        url: https://s3-us-west-2.amazonaws.com/fm.ethan.jason/4766FA79-8908-4561-899B-E0FFE097FC40.jpeg
        __v: 0
      - _id: 581feae8d6e05303005f920b
        url: https://s3-us-west-2.amazonaws.com/fm.ethan.jason/6F30F374-AD8A-46CD-B02E-D88350ED0F5D.jpeg
        __v: 0
      - _id: 581f638494f6b30300a371fe
        url: https://s3-us-west-2.amazonaws.com/fm.ethan.jason/7662CB2F-822D-4EB7-8ECA-13EBE22E07B8.jpeg
        __v: 0
      - _id: 580f0c0f99c71a0300137a40
        url: https://s3-us-west-2.amazonaws.com/fm.ethan.jason/9504C536-7352-4C0D-BDB5-A7564D36F282.jpeg
        __v: 0
      - _id: 5806b9e1c9803f0300800ea4
        url: https://s3-us-west-2.amazonaws.com/fm.ethan.jason/BF2F5DD1-B929-4BBB-893F-6DBF3130C00D.jpeg
        __v: 0
      - _id: 57fef2e8a7d9ac0300a3203e
        url: https://s3-us-west-2.amazonaws.com/fm.ethan.jason/A5BFD3AC-A4D3-4DBC-B4FB-22CBBA7CE500.jpeg
        __v: 0
      - _id: 57f684aa2838180300e2fc35
        url: https://s3-us-west-2.amazonaws.com/fm.ethan.jason/037D6539-CCCA-4F8F-AC47-117796D3C3D6.jpeg
        __v: 0
      - _id: 57ead0601e3bfb03002fea15
        url: https://s3-us-west-2.amazonaws.com/fm.ethan.jason/F4425082-5E76-47E2-B7E7-8EDABB9BD73F.jpeg
        __v: 0
      - _id: 57bf5a85d4ed5103002b712a
        url: https://s3-us-west-2.amazonaws.com/fm.ethan.jason/DEEFCD96-CAF0-4529-A896-CC14BB34E443.jpeg
        __v: 0
      - _id: 57bc81d7d58e2f03005573b8
        url: https://s3-us-west-2.amazonaws.com/fm.ethan.jason/4BBFB817-93F1-474E-A179-B0462BB68016.jpeg
        __v: 0
      - _id: 57bb715ca56d200300df67c9
        url: https://s3-us-west-2.amazonaws.com/fm.ethan.jason/D3BDA263-BAB1-4114-89A5-8CB8B1F76020.jpeg
        __v: 0
      - _id: 57bb70d8a67a2703007b4053
        url: https://s3-us-west-2.amazonaws.com/fm.ethan.jason/4449D16F-D4B6-4868-BD56-8E217AC85756.jpeg
        __v: 0
      - _id: 576f8d1521deda0300f370e5
        url: https://s3-us-west-2.amazonaws.com/fm.ethan.jason/BA46A4BA-C113-430C-BDA3-412AF6398C43.jpeg
        __v: 0
      - _id: 576f8d0121deda0300f370e4
        url: https://s3-us-west-2.amazonaws.com/fm.ethan.jason/EDAF76DF-5428-4E9E-998B-7CF2200D51B8.jpeg
        __v: 0
      - _id: 573696c686be6003009f7621
        url: https://s3-us-west-2.amazonaws.com/fm.ethan.jason/FDE039DA-8178-4EB5-81AC-57651F57D333.jpeg
        __v: 0
      - _id: 573695b586be6003009f7620
        url: https://s3-us-west-2.amazonaws.com/fm.ethan.jason/F907B98F-72D2-4F76-A9D1-4BC849AE95B4.jpeg
        __v: 0
      - _id: 5736918186be6003009f761f
        url: https://s3-us-west-2.amazonaws.com/fm.ethan.jason/C80C0D52-8ABB-4556-AB34-FB16BC2D45B8.jpeg
        __v: 0
      - _id: 573690f686be6003009f761e
        url: https://s3-us-west-2.amazonaws.com/fm.ethan.jason/7C7222B0-2EB4-47B3-A721-1B77C78C6BC8.jpeg
        __v: 0
      - _id: 573690a986be6003009f761d
        url: https://s3-us-west-2.amazonaws.com/fm.ethan.jason/4981B329-62CB-466F-9F1B-569BDE5060E1.jpeg
        __v: 0
      - _id: 571a4ebe44096303002092f4
        url: https://s3-us-west-2.amazonaws.com/fm.ethan.jason/CD8D15B0-978A-4823-A687-F048EA728257.jpeg
        __v: 0
      - _id: 571a4e9144096303002092f3
        url: https://s3-us-west-2.amazonaws.com/fm.ethan.jason/45C8A405-FD8E-4574-B155-3B84BD902B5E.jpeg
        __v: 0
      - _id: 5719a2cd6bb4cc03002f5bbf
        url: https://s3-us-west-2.amazonaws.com/fm.ethan.jason/6693C2F6-8830-41ED-8B7D-49CB22FE1E01.jpeg
        __v: 0
      - _id: 5719907f1aa0f80300c55277
        url: https://s3-us-west-2.amazonaws.com/fm.ethan.jason/5F6CD831-3F6A-4F81-90B1-4BE744EC73EA.jpeg
        __v: 0
      - _id: 571982bd0eb36403003c681f
        url: https://s3-us-west-2.amazonaws.com/fm.ethan.jason/C4B3C0D9-1D7A-4F76-9F13-C4E549A8179E.jpeg
        __v: 0
      - _id: 571978ca414fc203003d8c3b
        url: https://s3-us-west-2.amazonaws.com/fm.ethan.jason/842AC9A6-308C-4777-8014-B1A3DDF0F69F.jpeg
        __v: 0
      - _id: 5719761e414fc203003d8c3a
        url: https://s3-us-west-2.amazonaws.com/fm.ethan.jason/3F1A0FFC-3A9A-4651-84F0-4D0BE0D5CAB7.jpeg
        __v: 0
      - _id: 571975079bb7260300cb1884
        url: https://s3-us-west-2.amazonaws.com/fm.ethan.jason/D2FAE975-2BB6-4077-8762-ECA703902914.jpeg
        __v: 0
      - _id: 571971ae0707630300a0c04b
        url: https://s3-us-west-2.amazonaws.com/fm.ethan.jason/B079FA13-373D-4F00-B948-3DF95457B376.jpeg
        __v: 0
      - _id: 5719514128437b0300833f5e
        url: https://s3-us-west-2.amazonaws.com/fm.ethan.jason/A6FBD9B2-AEDC-49C7-8A35-820A62C6309F.jpeg
        __v: 0
      - _id: 5719512628437b0300833f5d
        url: https://s3-us-west-2.amazonaws.com/fm.ethan.jason/2A5928B5-A1E7-4256-B012-1C871A779842.jpeg
        __v: 0
    actions:
      "$load":
        type: "$set"
        options:
          selected: ''
        success:
          type: "$render"
      "$pull":
        type: "$media.camera"
        options:
          quality: '0.4'
        success:
          type: "$network.upload"
          options:
            type: s3
            bucket: fm.ethan.jason
            data: "{{$jason.data}}"
            content_type: "{{$jason.content_type}}"
            path: ''
            sign_url: https://imagejason.herokuapp.com/sign_url
          success:
            type: "$network.request"
            options:
              url: https://imagejason.herokuapp.com/post
              method: post
              data:
                bucket: fm.ethan.jason
                path: "/"
                filename: "{{$jason.filename}}"
            success:
              type: "$reload"
    templates:
      body:
        style:
          border: none
        header:
          menu:
            text: View Full Source
            href:
              url: https://github.com/Jasonette/s3-upload-example/blob/master/app.js
              view: web
        sections:
        - style:
            spacing: '0'
            padding: '0'
          header:
            type: vertical
            style:
              align: center
              padding: '20'
              z_index: "-1"
            components:
            - type: image
              url: https://d30y9cdsu7xlg0.cloudfront.net/png/126349-200.png
              style:
                z_index: "-1"
                width: '100'
          items:
          - "{{#if db && db.length > 0}}":
              "{{#each db}}":
                type: image
                style:
                  width: 100%
                  padding: '0'
                url: "{{url}}"
          - "{{#else}}": []
```
